
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kira
 */
public class EnregistrerUnFournisseur extends javax.swing.JFrame {

    /**
     * Creates new form EnregistrerUnClient
     */
    public EnregistrerUnFournisseur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PrenomClient1 = new javax.swing.JLabel();
        Civilite1 = new javax.swing.JLabel();
        Ville1 = new javax.swing.JLabel();
        Codepostal1 = new javax.swing.JLabel();
        Societe1 = new javax.swing.JLabel();
        Pays1 = new javax.swing.JLabel();
        Ville = new javax.swing.JTextField();
        Pays = new javax.swing.JTextField();
        CodePostal = new javax.swing.JTextField();
        Telephone = new javax.swing.JTextField();
        Telephone1 = new javax.swing.JLabel();
        Fax = new javax.swing.JTextField();
        Societe = new javax.swing.JTextField();
        Mobile1 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        Fax1 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Email1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Adresse = new javax.swing.JTextArea();
        Adresse1 = new javax.swing.JLabel();
        EnregistrerClient = new javax.swing.JButton();
        NumFournisseur = new javax.swing.JTextField();
        Retour = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        NomFournisseur = new javax.swing.JTextField();
        Civilite = new javax.swing.JComboBox<>();
        Prenom = new javax.swing.JTextField();
        NumFournisseur1 = new javax.swing.JLabel();
        NomFournisseur1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enregistrement");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        PrenomClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PrenomClient1.setText("Prenom :");

        Civilite1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Civilite1.setText("Civilité :");

        Ville1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Ville1.setText("Ville :");

        Codepostal1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Codepostal1.setText("Code postal :");

        Societe1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Societe1.setText("Société :");

        Pays1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Pays1.setText("Pays :");

        Ville.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Ville.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VilleKeyPressed(evt);
            }
        });

        Pays.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Pays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PaysKeyPressed(evt);
            }
        });

        CodePostal.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        CodePostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodePostalKeyPressed(evt);
            }
        });

        Telephone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Telephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TelephoneKeyPressed(evt);
            }
        });

        Telephone1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Telephone1.setText("Telephone :");

        Fax.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FaxKeyPressed(evt);
            }
        });

        Societe.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Societe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SocieteKeyPressed(evt);
            }
        });

        Mobile1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Mobile1.setText("Mobile :");

        Mobile.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MobileKeyPressed(evt);
            }
        });

        Fax1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Fax1.setText("Fax :");

        Email.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailKeyPressed(evt);
            }
        });

        Email1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Email1.setText("Email :");

        Adresse.setColumns(20);
        Adresse.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Adresse.setRows(5);
        Adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AdresseKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Adresse);

        Adresse1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Adresse1.setText("Adresse :");

        EnregistrerClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        EnregistrerClient.setText("Enregistrer");
        EnregistrerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerClientActionPerformed(evt);
            }
        });

        NumFournisseur.setEditable(false);
        NumFournisseur.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        NumFournisseur.setEnabled(false);

        Retour.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Annuler.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });

        NomFournisseur.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        NomFournisseur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomFournisseurKeyPressed(evt);
            }
        });

        Civilite.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Civilite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M.", "Mme.", "Mlle." }));

        Prenom.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrenomKeyPressed(evt);
            }
        });

        NumFournisseur1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumFournisseur1.setText("N°Fournisseur :");

        NomFournisseur1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NomFournisseur1.setText("Nom :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nouveau dossier/Ajouter_fourn.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumFournisseur1)
                                    .addComponent(NomFournisseur1)
                                    .addComponent(PrenomClient1)
                                    .addComponent(Civilite1)
                                    .addComponent(Societe1)
                                    .addComponent(Adresse1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Societe, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomFournisseur, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(Prenom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumFournisseur, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Civilite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pays1)
                                    .addComponent(Telephone1)
                                    .addComponent(Fax1)
                                    .addComponent(Ville1)
                                    .addComponent(Codepostal1)
                                    .addComponent(Mobile1)
                                    .addComponent(Email1))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Fax, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telephone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pays, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ville, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodePostal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Mobile)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(EnregistrerClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumFournisseur1)
                    .addComponent(Codepostal1)
                    .addComponent(CodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomFournisseur1)
                    .addComponent(NomFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ville1)
                    .addComponent(Ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomClient1)
                    .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pays1)
                    .addComponent(Pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Civilite1)
                    .addComponent(Telephone1)
                    .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Civilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Societe1)
                    .addComponent(Societe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fax1)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Adresse1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Mobile1)
                                .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email1)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnregistrerClient)
                    .addComponent(Retour)
                    .addComponent(Annuler))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
       BienVenu I = new BienVenu();
        I.show();
        this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    private void EnregistrerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerClientActionPerformed
        Fournisseur fournisseur = new Fournisseur();
        DB.AutoNumFournisseur();
        NumFournisseur.setText(Integer.toString(DB.Num));
        fournisseur.setNum(Integer.parseInt(NumFournisseur.getText()));
        fournisseur.setNomClient(NomFournisseur.getText());
        fournisseur.setPrenom(Prenom.getText());
        fournisseur.setAdresse(Adresse.getText());
        fournisseur.setCivilite(Civilite.getSelectedItem().toString());
        fournisseur.setSociete(Societe.getText());
        fournisseur.setEmail(Email.getText());
        fournisseur.setVille(Ville.getText());
        fournisseur.setPays(Pays.getText());
        fournisseur.setTelephone(Telephone.getText());
        fournisseur.setMobile(Mobile.getText());
        fournisseur.setFax(Fax.getText());
        fournisseur.setCodePostal(CodePostal.getText());
        DB.InsertDB(fournisseur);
         JOptionPane.showMessageDialog( null, "Succès!", 
					      "Fournisseur Enregistré(e)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_EnregistrerClientActionPerformed

    private void NomFournisseurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomFournisseurKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Prenom.grabFocus();
            }
    }//GEN-LAST:event_NomFournisseurKeyPressed

    private void PrenomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Civilite.grabFocus();
            }
    }//GEN-LAST:event_PrenomKeyPressed

    private void SocieteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SocieteKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Adresse.grabFocus();
            }
    }//GEN-LAST:event_SocieteKeyPressed

    private void AdresseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdresseKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              CodePostal.grabFocus();
            }
    }//GEN-LAST:event_AdresseKeyPressed

    private void CodePostalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodePostalKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Ville.grabFocus();
            }
    }//GEN-LAST:event_CodePostalKeyPressed

    private void VilleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VilleKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Pays.grabFocus();
            }
    }//GEN-LAST:event_VilleKeyPressed

    private void PaysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaysKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Telephone.grabFocus();
            }
    }//GEN-LAST:event_PaysKeyPressed

    private void TelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelephoneKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Fax.grabFocus();
            }
    }//GEN-LAST:event_TelephoneKeyPressed

    private void FaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FaxKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Mobile.grabFocus();
            }
    }//GEN-LAST:event_FaxKeyPressed

    private void MobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MobileKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              Email.grabFocus();
            }
    }//GEN-LAST:event_MobileKeyPressed

    private void EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
            {
              NomFournisseur.grabFocus();
            }// TODO add your handling code here:
    }//GEN-LAST:event_EmailKeyPressed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        
                NumFournisseur.setText("");
                NomFournisseur.setText("");
                Prenom.setText("");
                Adresse.setText("");
                Civilite.setSelectedIndex(0);
                Societe.setText("");
                Email.setText("");
                Ville.setText("");
                Pays.setText("");
                Telephone.setText("");
                Mobile.setText("");
                Fax.setText("");
                CodePostal.setText("");
        
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerUnClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Adresse;
    private javax.swing.JLabel Adresse1;
    private javax.swing.JButton Annuler;
    public static javax.swing.JComboBox<String> Civilite;
    private javax.swing.JLabel Civilite1;
    private javax.swing.JTextField CodePostal;
    private javax.swing.JLabel Codepostal1;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JButton EnregistrerClient;
    private javax.swing.JTextField Fax;
    private javax.swing.JLabel Fax1;
    private javax.swing.JTextField Mobile;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JTextField NomFournisseur;
    private javax.swing.JLabel NomFournisseur1;
    private javax.swing.JTextField NumFournisseur;
    private javax.swing.JLabel NumFournisseur1;
    private javax.swing.JTextField Pays;
    private javax.swing.JLabel Pays1;
    private javax.swing.JTextField Prenom;
    private javax.swing.JLabel PrenomClient1;
    private javax.swing.JButton Retour;
    private javax.swing.JTextField Societe;
    private javax.swing.JLabel Societe1;
    private javax.swing.JTextField Telephone;
    private javax.swing.JLabel Telephone1;
    private javax.swing.JTextField Ville;
    private javax.swing.JLabel Ville1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
