
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kira
 */
public class Factures extends javax.swing.JFrame {

    /**
     * Creates new form EnregistrerUnClient
     */
    public Factures() {
        initComponents();
        lignefac.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 15));
        Actualiser(0);
    }
    
    void Actualiser(int j) {
        
        DB.SelectNumClientDB();
        NumClient.removeAllItems();
        for(int i=0; i<DB.clients.size(); i++) {
            NumClient.addItem(DB.clients.get(i).getNum());
        }
        
        DB.SelectIDModeRegelementDB();
        ModeReglement.removeAllItems();
        for(int i=0; i<DB.DMs.size(); i++) {
            ModeReglement.addItem(DB.DMs.get(i));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaisiLeJ1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AdresseFacturation = new javax.swing.JTextArea();
        DateFacture = new javax.swing.JTextField();
        Imprimer = new javax.swing.JButton();
        TotalHT = new javax.swing.JTextField();
        SaisiLe = new javax.swing.JTextField();
        ModeReglement1 = new javax.swing.JLabel();
        ModeReglement = new javax.swing.JComboBox<>();
        TotalTVA1 = new javax.swing.JLabel();
        TotalTVA = new javax.swing.JTextField();
        TotalTTC1 = new javax.swing.JLabel();
        TotalTTC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lignefac = new javax.swing.JTable();
        SaisiPar1 = new javax.swing.JLabel();
        SaisiLe1 = new javax.swing.JLabel();
        Enregistrer = new javax.swing.JButton();
        NumClient1 = new javax.swing.JLabel();
        Nouvelle1 = new javax.swing.JButton();
        AdresseFacturation1 = new javax.swing.JLabel();
        Suivant = new javax.swing.JButton();
        Observation1 = new javax.swing.JLabel();
        Precedant = new javax.swing.JButton();
        NumFacture1 = new javax.swing.JLabel();
        Dernier = new javax.swing.JButton();
        SaisiPar = new javax.swing.JTextField();
        Premier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observation = new javax.swing.JTextArea();
        Retour = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        NumClient = new javax.swing.JComboBox<>();
        NumFacture = new javax.swing.JTextField();
        DateFacture1 = new javax.swing.JLabel();
        TotalHT1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        SaisiLeJ1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factures");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        AdresseFacturation.setColumns(20);
        AdresseFacturation.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        AdresseFacturation.setRows(5);
        jScrollPane3.setViewportView(AdresseFacturation);

        DateFacture.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Imprimer.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Imprimer.setText("Imprimer");

        TotalHT.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TotalHT.setText("0.00");

        SaisiLe.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        ModeReglement1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ModeReglement1.setText("Mode Réglement :");

        ModeReglement.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        TotalTVA1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        TotalTVA1.setText("Total TVA :");

        TotalTVA.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TotalTVA.setText("0.00");

        TotalTTC1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        TotalTTC1.setText("Total TTC :");

        TotalTTC.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        TotalTTC.setText("0.00");

        lignefac.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        lignefac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Facture", "Réference", "Libéllé Produit", "Quantité", "Prix Vente", "Remise", "Taux TVA", "Ordre d'affichage", "ID Commande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        lignefac.setToolTipText("");
        lignefac.setRowHeight(30);
        jScrollPane2.setViewportView(lignefac);

        SaisiPar1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SaisiPar1.setText("Saisi Par :");

        SaisiLe1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SaisiLe1.setText("Saisi Le :");

        Enregistrer.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Enregistrer.setText("Enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });

        NumClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumClient1.setText("N° Client :");

        Nouvelle1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Nouvelle1.setText("Nouvelle");
        Nouvelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nouvelle1ActionPerformed(evt);
            }
        });

        AdresseFacturation1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        AdresseFacturation1.setText("Adresse Facturation :");

        Suivant.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Suivant.setText(">");
        Suivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuivantActionPerformed(evt);
            }
        });

        Observation1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Observation1.setText("Observation :");

        Precedant.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Precedant.setText("<");
        Precedant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecedantActionPerformed(evt);
            }
        });

        NumFacture1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumFacture1.setText("N° Facture :");

        Dernier.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Dernier.setText(">>");
        Dernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DernierActionPerformed(evt);
            }
        });

        SaisiPar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Premier.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Premier.setText("<<");
        Premier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremierActionPerformed(evt);
            }
        });

        Observation.setColumns(20);
        Observation.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Observation.setRows(5);
        jScrollPane1.setViewportView(Observation);

        Retour.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        Supprimer.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerActionPerformed(evt);
            }
        });

        NumClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        NumFacture.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        DateFacture1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        DateFacture1.setText("Date Facture :");

        TotalHT1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        TotalHT1.setText("Total HT :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nouveau dossier/facture.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Observation1)
                                    .addComponent(SaisiPar1)
                                    .addComponent(SaisiLe1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(SaisiLe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(434, 434, 434)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalHT1)
                                            .addComponent(TotalTVA1)
                                            .addComponent(TotalTTC1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TotalTTC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalHT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SaisiPar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addComponent(Premier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Precedant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Suivant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dernier)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nouvelle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Retour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumFacture1)
                            .addComponent(DateFacture1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(NumFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DateFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumClient1)
                                    .addComponent(ModeReglement1))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModeReglement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumClient, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(AdresseFacturation1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AdresseFacturation1)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumClient1)
                                    .addComponent(NumFacture1)
                                    .addComponent(NumFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModeReglement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModeReglement1)
                            .addComponent(DateFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateFacture1)))
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nouvelle1)
                        .addGap(18, 18, 18)
                        .addComponent(Supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Imprimer)
                        .addGap(18, 18, 18)
                        .addComponent(Retour)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalHT1)
                            .addComponent(TotalHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalTVA1)
                            .addComponent(TotalTVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalTTC1)
                            .addComponent(TotalTTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Suivant)
                            .addComponent(Precedant)
                            .addComponent(Dernier)
                            .addComponent(Premier)
                            .addComponent(Enregistrer))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaisiPar1)
                                .addComponent(SaisiPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SaisiLe1)
                                .addComponent(SaisiLe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Observation1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        BienVenu I=new BienVenu();
        I.show();
        this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    private void Nouvelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nouvelle1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) lignefac.getModel();
        model.addRow(new Object[]{"", "", "", "", "", "", "", "", ""});
        System.out.println(model.getRowCount());
        
    }//GEN-LAST:event_Nouvelle1ActionPerformed

    private void SupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) lignefac.getModel();
        int[] rows = lignefac.getSelectedRows();
        for(int i=0;i<rows.length;i++)model.removeRow(rows[i]-i);
    }//GEN-LAST:event_SupprimerActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        if(Move==-1) {
        DefaultTableModel model = (DefaultTableModel) lignefac.getModel();
        Facture facture = new Facture();
        
        facture.setNumFacture(Integer.parseInt(NumFacture.getText()));
        facture.setDateFacture(DateFacture.getText());
        facture.setNumClient(Integer.parseInt(NumClient.getSelectedItem().toString()));
        facture.setIDAdresseFacturation(Integer.parseInt(NumClient.getSelectedItem().toString()));
        facture.setIDModeReglement(ModeReglement.getSelectedIndex()+1);
        facture.setTotalHT(Double.parseDouble(TotalHT.getText()));
        facture.setTotalTVA(Double.parseDouble(TotalTVA.getText()));
        facture.setTotalTTC(Double.parseDouble(TotalTTC.getText()));
        facture.setSaisiPar(SaisiPar.getText());
        facture.setSaisiLe(SaisiLe.getText());
        facture.setObservation(Observation.getText());
        
        int[] IDLigneFac = new int[model.getRowCount()],
              Quantite = new int[model.getRowCount()],
              IDLigneCde = new int[model.getRowCount()],
              OrdreAffichage = new int[model.getRowCount()];
        String[] Reference = new String[model.getRowCount()],
                 LibProd = new String[model.getRowCount()];
        double[] PrixVente = new double[model.getRowCount()],
                 Remise = new double[model.getRowCount()],
                 TauxTVA = new double[model.getRowCount()];
        
        
        for(int i=0; i<model.getRowCount(); i++) {
            IDLigneFac[i] = Integer.parseInt(model.getValueAt(i,0).toString());
            Reference[i] = model.getValueAt(i,1).toString();
            LibProd[i] = model.getValueAt(i,2).toString();
            Quantite[i] = Integer.parseInt(model.getValueAt(i,3).toString());
            PrixVente[i] = Double.parseDouble(model.getValueAt(i,4).toString());
            Remise[i] = Double.parseDouble(model.getValueAt(i,5).toString());
            TauxTVA[i] = Double.parseDouble(model.getValueAt(i,6).toString());
            OrdreAffichage[i] = Integer.parseInt(model.getValueAt(i,7).toString());
            IDLigneCde[i] = Integer.parseInt(model.getValueAt(i,8).toString());
        }
        
        facture.setIDLigneFac(IDLigneFac);
        facture.setReference(Reference);
        facture.setLibProd(LibProd);
        facture.setQuantite(Quantite);
        facture.setPrixVente(PrixVente);
        facture.setRemise(Remise);
        facture.setTauxTVA(TauxTVA);
        facture.setOrdreAffichage(OrdreAffichage);
        facture.setIDLigneCde(IDLigneCde);
        
        DB.InsertDB(facture);
         JOptionPane.showMessageDialog( null, "Succès!", 
					      "Facture Enregistrée", JOptionPane.INFORMATION_MESSAGE);
        }
         
    }//GEN-LAST:event_EnregistrerActionPerformed

    int Move=-1;
    private void SuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuivantActionPerformed
        DB.SelectNumFactureDB();
        if(!DB.factures.isEmpty() && Move<DB.factures.size()-1) {
            Move++;
            NumFacture.setText(Integer.toString(DB.factures.get(Move).getNumFacture()));
        }
    }//GEN-LAST:event_SuivantActionPerformed

    private void PrecedantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecedantActionPerformed
        DB.SelectNumFactureDB();
        if(!DB.factures.isEmpty() && Move>0) {
            Move--;
            NumFacture.setText(Integer.toString(DB.factures.get(Move).getNumFacture()));
        }
        if(Move==0) {
            Move=-1;
            NumFacture.setText("");
        }
    }//GEN-LAST:event_PrecedantActionPerformed

    private void DernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DernierActionPerformed
        DB.SelectNumFactureDB();
        if(!DB.factures.isEmpty()) {
            Move=DB.factures.size()-1;
            NumFacture.setText(Integer.toString(DB.factures.get(Move).getNumFacture()));
        }
    }//GEN-LAST:event_DernierActionPerformed

    private void PremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremierActionPerformed
        DB.SelectNumFactureDB();
        if(!DB.factures.isEmpty() && Move!=-1) {
            Move=0;
            NumFacture.setText(Integer.toString(DB.factures.get(Move).getNumFacture()));
        }
    }//GEN-LAST:event_PremierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerUnClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AdresseFacturation;
    private javax.swing.JLabel AdresseFacturation1;
    private javax.swing.JTextField DateFacture;
    private javax.swing.JLabel DateFacture1;
    private javax.swing.JButton Dernier;
    private javax.swing.JButton Enregistrer;
    private javax.swing.JButton Imprimer;
    private javax.swing.JComboBox<String> ModeReglement;
    private javax.swing.JLabel ModeReglement1;
    private javax.swing.JButton Nouvelle1;
    private javax.swing.JComboBox<String> NumClient;
    private javax.swing.JLabel NumClient1;
    private javax.swing.JTextField NumFacture;
    private javax.swing.JLabel NumFacture1;
    private javax.swing.JTextArea Observation;
    private javax.swing.JLabel Observation1;
    private javax.swing.JButton Precedant;
    private javax.swing.JButton Premier;
    private javax.swing.JButton Retour;
    private javax.swing.JTextField SaisiLe;
    private javax.swing.JLabel SaisiLe1;
    private javax.swing.JComboBox<String> SaisiLeJ1;
    private javax.swing.JTextField SaisiPar;
    private javax.swing.JLabel SaisiPar1;
    private javax.swing.JButton Suivant;
    private javax.swing.JButton Supprimer;
    private javax.swing.JTextField TotalHT;
    private javax.swing.JLabel TotalHT1;
    private javax.swing.JTextField TotalTTC;
    private javax.swing.JLabel TotalTTC1;
    private javax.swing.JTextField TotalTVA;
    private javax.swing.JLabel TotalTVA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lignefac;
    // End of variables declaration//GEN-END:variables
}
