/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kira
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifierClient = new javax.swing.JButton();
        EnregistrerClient = new javax.swing.JButton();
        ConsulterClients = new javax.swing.JButton();
        SeDeconnecter = new javax.swing.JButton();
        SupprimerClient1 = new javax.swing.JButton();
        EnregistrerFourniseur = new javax.swing.JButton();
        ConsulterFourniseurs = new javax.swing.JButton();
        SupprimerFourniseur = new javax.swing.JButton();
        ModifierFourniseur = new javax.swing.JButton();
        Clients = new javax.swing.JLabel();
        Fourniseurs = new javax.swing.JLabel();
        ConsulterProduits = new javax.swing.JButton();
        SupprimerProduit = new javax.swing.JButton();
        ModifierProduit = new javax.swing.JButton();
        EnregistrerProduit = new javax.swing.JButton();
        Produits = new javax.swing.JLabel();
        Factures = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenu(e)");

        ModifierClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ModifierClient.setText("Modifier Un Client");
        ModifierClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierClientActionPerformed(evt);
            }
        });

        EnregistrerClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        EnregistrerClient.setText("Enregistrer Un Client");
        EnregistrerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerClientActionPerformed(evt);
            }
        });

        ConsulterClients.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ConsulterClients.setText("Consulter La Liste Des Clients");
        ConsulterClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterClientsActionPerformed(evt);
            }
        });

        SeDeconnecter.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SeDeconnecter.setText("Se Déconnecter");
        SeDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeDeconnecterActionPerformed(evt);
            }
        });

        SupprimerClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SupprimerClient1.setText("Supprimer Un Client");
        SupprimerClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerClient1ActionPerformed(evt);
            }
        });

        EnregistrerFourniseur.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        EnregistrerFourniseur.setText("Enregistrer Un Fourniseur");
        EnregistrerFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerFourniseurActionPerformed(evt);
            }
        });

        ConsulterFourniseurs.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ConsulterFourniseurs.setText("Consulter La Liste Des Fourniseurs");
        ConsulterFourniseurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterFourniseursActionPerformed(evt);
            }
        });

        SupprimerFourniseur.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SupprimerFourniseur.setText("Supprimer Un Fourniseur");
        SupprimerFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerFourniseurActionPerformed(evt);
            }
        });

        ModifierFourniseur.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ModifierFourniseur.setText("Modifier Un Fourniseur");
        ModifierFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierFourniseurActionPerformed(evt);
            }
        });

        Clients.setText("Clients :");

        Fourniseurs.setText("Fourniseurs :");

        ConsulterProduits.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ConsulterProduits.setText("Consulter La Liste Des Produits");
        ConsulterProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterProduitsActionPerformed(evt);
            }
        });

        SupprimerProduit.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SupprimerProduit.setText("Supprimer Un Produit");
        SupprimerProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerProduitActionPerformed(evt);
            }
        });

        ModifierProduit.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ModifierProduit.setText("Modifier Un Produit");
        ModifierProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierProduitActionPerformed(evt);
            }
        });

        EnregistrerProduit.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        EnregistrerProduit.setText("Enregistrer Un Produit");
        EnregistrerProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerProduitActionPerformed(evt);
            }
        });

        Produits.setText("Produits :");

        Factures.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Factures.setText("Factures");
        Factures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(Clients)
                        .addGap(282, 282, 282))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Factures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConsulterClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnregistrerClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ModifierClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupprimerClient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(Fourniseurs))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EnregistrerFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ModifierFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SupprimerFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ConsulterFourniseurs, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Produits))
                    .addComponent(EnregistrerProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifierProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SupprimerProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConsulterProduits, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SeDeconnecter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Clients)
                        .addGap(18, 18, 18)
                        .addComponent(EnregistrerClient)
                        .addGap(18, 18, 18)
                        .addComponent(ModifierClient, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SupprimerClient1)
                        .addGap(18, 18, 18)
                        .addComponent(ConsulterClients)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeDeconnecter)
                            .addComponent(Factures)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Produits)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EnregistrerProduit)
                                .addGap(18, 18, 18)
                                .addComponent(ModifierProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SupprimerProduit)
                                .addGap(18, 18, 18)
                                .addComponent(ConsulterProduits))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fourniseurs)
                                .addGap(18, 18, 18)
                                .addComponent(EnregistrerFourniseur)
                                .addGap(18, 18, 18)
                                .addComponent(ModifierFourniseur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SupprimerFourniseur)
                                .addGap(18, 18, 18)
                                .addComponent(ConsulterFourniseurs))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierClientActionPerformed
        ModifierUnClient I = new ModifierUnClient();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ModifierClientActionPerformed

    private void EnregistrerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerClientActionPerformed
        EnregistrerUnClient I = new EnregistrerUnClient();
        I.show();
        this.dispose();
    }//GEN-LAST:event_EnregistrerClientActionPerformed

    private void ConsulterClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterClientsActionPerformed
        ConsulterListeClients I = new ConsulterListeClients();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ConsulterClientsActionPerformed

    private void SeDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeDeconnecterActionPerformed
        DB.CloseDB();
        SeConnecter I = new SeConnecter();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SeDeconnecterActionPerformed

    private void SupprimerClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerClient1ActionPerformed
        SupprimerUnClient I = new SupprimerUnClient();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SupprimerClient1ActionPerformed

    private void EnregistrerFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerFourniseurActionPerformed
        EnregistrerUnFournisseur I = new EnregistrerUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_EnregistrerFourniseurActionPerformed

    private void ConsulterFourniseursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterFourniseursActionPerformed
        ConsulterListeFournisseurs I = new ConsulterListeFournisseurs();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ConsulterFourniseursActionPerformed

    private void SupprimerFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerFourniseurActionPerformed
        SupprimerUnFournisseur I = new SupprimerUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SupprimerFourniseurActionPerformed

    private void ModifierFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierFourniseurActionPerformed
        ModifierUnFournisseur I = new ModifierUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ModifierFourniseurActionPerformed

    private void ConsulterProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterProduitsActionPerformed
        ConsulterListeProduits I = new ConsulterListeProduits();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ConsulterProduitsActionPerformed

    private void SupprimerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerProduitActionPerformed
        SupprimerUnProduit I = new SupprimerUnProduit();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SupprimerProduitActionPerformed

    private void ModifierProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierProduitActionPerformed
        ModifierUnProduit I = new ModifierUnProduit();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ModifierProduitActionPerformed

    private void EnregistrerProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerProduitActionPerformed
        EnregistrerUnProduit I = new EnregistrerUnProduit();
        I.show();
        this.dispose();
    }//GEN-LAST:event_EnregistrerProduitActionPerformed

    private void FacturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturesActionPerformed
        Factures I = new Factures();
        I.show();
        this.dispose();
    }//GEN-LAST:event_FacturesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clients;
    private javax.swing.JButton ConsulterClients;
    private javax.swing.JButton ConsulterFourniseurs;
    private javax.swing.JButton ConsulterProduits;
    private javax.swing.JButton EnregistrerClient;
    private javax.swing.JButton EnregistrerFourniseur;
    private javax.swing.JButton EnregistrerProduit;
    private javax.swing.JButton Factures;
    private javax.swing.JLabel Fourniseurs;
    private javax.swing.JButton ModifierClient;
    private javax.swing.JButton ModifierFourniseur;
    private javax.swing.JButton ModifierProduit;
    private javax.swing.JLabel Produits;
    private javax.swing.JButton SeDeconnecter;
    private javax.swing.JButton SupprimerClient1;
    private javax.swing.JButton SupprimerFourniseur;
    private javax.swing.JButton SupprimerProduit;
    // End of variables declaration//GEN-END:variables
}
