/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO-G50
 */
public class Jframe_Fournisseur extends javax.swing.JFrame {

    /**
     * Creates new form Jframe_Fournisseur
     */
    public Jframe_Fournisseur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConsulterFourniseurs = new javax.swing.JButton();
        SupprimerFourniseur = new javax.swing.JButton();
        ModifierFourniseur = new javax.swing.JButton();
        Fourniseurs = new javax.swing.JLabel();
        EnregistrerFourniseur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SeDeconnecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        ConsulterFourniseurs.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ConsulterFourniseurs.setText("Consulter La Liste Des Fourniseurs");
        ConsulterFourniseurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterFourniseursActionPerformed(evt);
            }
        });

        SupprimerFourniseur.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        SupprimerFourniseur.setText("Supprimer Un Fourniseur");
        SupprimerFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerFourniseurActionPerformed(evt);
            }
        });

        ModifierFourniseur.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        ModifierFourniseur.setText("Modifier Un Fourniseur");
        ModifierFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierFourniseurActionPerformed(evt);
            }
        });

        Fourniseurs.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Fourniseurs.setText("Fourniseurs :");

        EnregistrerFourniseur.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        EnregistrerFourniseur.setText("Ajouter Un Fourniseur");
        EnregistrerFourniseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerFourniseurActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nouveau dossier/fournisseur.PNG"))); // NOI18N

        SeDeconnecter.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        SeDeconnecter.setText("Se Déconnecter");
        SeDeconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeDeconnecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EnregistrerFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ModifierFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupprimerFourniseur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConsulterFourniseurs, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Fourniseurs)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeDeconnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Fourniseurs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(EnregistrerFourniseur)
                .addGap(18, 18, 18)
                .addComponent(ModifierFourniseur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SupprimerFourniseur)
                .addGap(18, 18, 18)
                .addComponent(ConsulterFourniseurs)
                .addGap(18, 18, 18)
                .addComponent(SeDeconnecter)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsulterFourniseursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterFourniseursActionPerformed
        ConsulterListeFournisseurs I = new ConsulterListeFournisseurs();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ConsulterFourniseursActionPerformed

    private void SupprimerFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerFourniseurActionPerformed
        SupprimerUnFournisseur I = new SupprimerUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SupprimerFourniseurActionPerformed

    private void ModifierFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierFourniseurActionPerformed
        ModifierUnFournisseur I = new ModifierUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_ModifierFourniseurActionPerformed

    private void EnregistrerFourniseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerFourniseurActionPerformed
        EnregistrerUnFournisseur I = new EnregistrerUnFournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_EnregistrerFourniseurActionPerformed

    private void SeDeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeDeconnecterActionPerformed
        DB.CloseDB();
        BienVenu I = new  BienVenu ();
        I.show();
        this.dispose();
    }//GEN-LAST:event_SeDeconnecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_Fournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_Fournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsulterFourniseurs;
    private javax.swing.JButton EnregistrerFourniseur;
    private javax.swing.JLabel Fourniseurs;
    private javax.swing.JButton ModifierFourniseur;
    private javax.swing.JButton SeDeconnecter;
    private javax.swing.JButton SupprimerFourniseur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
