
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kira
 */
public class ModifierUnFournisseur extends javax.swing.JFrame {

    /**
     * Creates new form EnregistrerUnClient
     */
    public ModifierUnFournisseur() {
        initComponents();
        Actualiser(0);
    }
    
    public void Actualiser(int j) {
        DB.SelectNumFournisseurDB();
        NumFournisseur.removeAllItems();
        for(int i=0; i<DB.fournisseurs.size(); i++) {
            NumFournisseur.addItem(DB.fournisseurs.get(i).getNum());
        }
        if(NumFournisseur.getItemCount() !=0) {
        
            NumFournisseur.setSelectedItem(DB.fournisseurs.get(j).getNum());
            NomFournisseur.setText(DB.fournisseurs.get(j).getNom());
            Prenom.setText(DB.fournisseurs.get(j).getPrenom());
            Adresse.setText(DB.fournisseurs.get(j).getAdresse());
            Civilite.setSelectedItem(DB.fournisseurs.get(j).getCivilite());
            Societe.setText(DB.fournisseurs.get(j).getSociete());
            Email.setText(DB.fournisseurs.get(j).getEmail());
            Ville.setText(DB.fournisseurs.get(j).getVille());
            Pays.setText(DB.fournisseurs.get(j).getPays());
            Telephone.setText(DB.fournisseurs.get(j).getTelephone());
            Mobile.setText(DB.fournisseurs.get(j).getMobile());
            Fax.setText(DB.fournisseurs.get(j).getFax());
            CodePostal.setText(DB.fournisseurs.get(j).getCodePostal());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CodePostal = new javax.swing.JTextField();
        Telephone = new javax.swing.JTextField();
        Fax = new javax.swing.JTextField();
        Societe = new javax.swing.JTextField();
        NumFournisseur1 = new javax.swing.JLabel();
        Mobile = new javax.swing.JTextField();
        NomFournisseur1 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        PrenomClient1 = new javax.swing.JLabel();
        NumFournisseur = new javax.swing.JComboBox<>();
        Civilite1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Adresse = new javax.swing.JTextArea();
        Ville1 = new javax.swing.JLabel();
        Codepostal1 = new javax.swing.JLabel();
        NomFournisseur = new javax.swing.JTextField();
        Societe1 = new javax.swing.JLabel();
        Pays1 = new javax.swing.JLabel();
        Civilite = new javax.swing.JComboBox<>();
        Telephone1 = new javax.swing.JLabel();
        Mobile1 = new javax.swing.JLabel();
        Fax1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        Adresse1 = new javax.swing.JLabel();
        ModifierClient = new javax.swing.JButton();
        Prenom = new javax.swing.JTextField();
        Ville = new javax.swing.JTextField();
        Pays = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modification");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        CodePostal.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Telephone.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Fax.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Societe.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        NumFournisseur1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumFournisseur1.setText("N°Fournisseur :");

        Mobile.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        NomFournisseur1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NomFournisseur1.setText("Nom :");

        Email.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        PrenomClient1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PrenomClient1.setText("Prenom :");

        NumFournisseur.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NumFournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumFournisseurActionPerformed(evt);
            }
        });

        Civilite1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Civilite1.setText("Civilité :");

        Adresse.setColumns(20);
        Adresse.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        Adresse.setRows(5);
        jScrollPane1.setViewportView(Adresse);

        Ville1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Ville1.setText("Ville :");

        Codepostal1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Codepostal1.setText("Code postal :");

        NomFournisseur.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Societe1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Societe1.setText("Société :");

        Pays1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Pays1.setText("Pays :");

        Civilite.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Civilite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M.", "Mme.", "Mlle." }));

        Telephone1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Telephone1.setText("Telephone :");

        Mobile1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Mobile1.setText("Mobile :");

        Fax1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Fax1.setText("Fax :");

        Email1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Email1.setText("Email :");

        Adresse1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Adresse1.setText("Adresse :");

        ModifierClient.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        ModifierClient.setText("Modifier");
        ModifierClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierClientActionPerformed(evt);
            }
        });

        Prenom.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Ville.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        Pays.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nouveau dossier/Modifier_fourn.PNG"))); // NOI18N

        Retour.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumFournisseur1)
                            .addComponent(NomFournisseur1)
                            .addComponent(PrenomClient1)
                            .addComponent(Civilite1)
                            .addComponent(Societe1)
                            .addComponent(Adresse1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Societe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumFournisseur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Prenom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomFournisseur, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Civilite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pays1)
                            .addComponent(Telephone1)
                            .addComponent(Fax1)
                            .addComponent(Ville1)
                            .addComponent(Codepostal1)
                            .addComponent(Mobile1)
                            .addComponent(Email1))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Fax, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telephone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pays, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ville, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodePostal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mobile)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ModifierClient, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(82, 82, 82)
                        .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumFournisseur1)
                    .addComponent(NumFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Codepostal1)
                    .addComponent(CodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomFournisseur1)
                    .addComponent(Ville1)
                    .addComponent(Ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomFournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrenomClient1)
                    .addComponent(Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pays1)
                    .addComponent(Pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Civilite1)
                    .addComponent(Telephone1)
                    .addComponent(Telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Civilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Societe1)
                    .addComponent(Societe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fax1)
                    .addComponent(Fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Adresse1)
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModifierClient)
                            .addComponent(Retour)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Mobile1)
                                .addComponent(Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email1)
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NumFournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumFournisseurActionPerformed
        int i=0;
        if (NumFournisseur.getSelectedIndex()!= -1) {
            while (Integer.parseInt(DB.fournisseurs.get(i).getNum()) != Integer.parseInt(NumFournisseur.getSelectedItem().toString())) i++;
            
            NomFournisseur.setText(DB.fournisseurs.get(i).getNom());
            Prenom.setText(DB.fournisseurs.get(i).getPrenom());
            Adresse.setText(DB.fournisseurs.get(i).getAdresse());
            Civilite.setSelectedItem(DB.fournisseurs.get(i).getCivilite());
            Societe.setText(DB.fournisseurs.get(i).getSociete());
            Email.setText(DB.fournisseurs.get(i).getEmail());
            CodePostal.setText(DB.fournisseurs.get(i).getCodePostal());
            Ville.setText(DB.fournisseurs.get(i).getVille());
            Pays.setText(DB.fournisseurs.get(i).getPays());
            Telephone.setText(DB.fournisseurs.get(i).getTelephone());
            Mobile.setText(DB.fournisseurs.get(i).getMobile());
            Fax.setText(DB.fournisseurs.get(i).getFax());
        }
        
    }//GEN-LAST:event_NumFournisseurActionPerformed

    private void ModifierClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierClientActionPerformed
        Fournisseur fournisseur = new Fournisseur();
        
        fournisseur.setNum(Integer.parseInt(NumFournisseur.getSelectedItem().toString()));
        fournisseur.setNomClient(NomFournisseur.getText());
        fournisseur.setPrenom(Prenom.getText());
        fournisseur.setAdresse(Adresse.getText());
        fournisseur.setCivilite(Civilite.getSelectedItem().toString());
        fournisseur.setSociete(Societe.getText());
        fournisseur.setEmail(Email.getText());
        fournisseur.setVille(Ville.getText());
        fournisseur.setPays(Pays.getText());
        fournisseur.setTelephone(Telephone.getText());
        fournisseur.setMobile(Mobile.getText());
        fournisseur.setFax(Fax.getText());
        fournisseur.setCodePostal(CodePostal.getText());
        DB.UpdateDB(fournisseur);
        Actualiser(NumFournisseur.getSelectedIndex());
         JOptionPane.showMessageDialog( null, "Succès!", 
					      "Fournisseur Modifié(e)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ModifierClientActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Jframe_Fournisseur I = new Jframe_Fournisseur();
        I.show();
        this.dispose();
    }//GEN-LAST:event_RetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerUnClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnregistrerUnClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Adresse;
    private javax.swing.JLabel Adresse1;
    public static javax.swing.JComboBox<String> Civilite;
    private javax.swing.JLabel Civilite1;
    private javax.swing.JTextField CodePostal;
    private javax.swing.JLabel Codepostal1;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Email1;
    private javax.swing.JTextField Fax;
    private javax.swing.JLabel Fax1;
    private javax.swing.JTextField Mobile;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JButton ModifierClient;
    private javax.swing.JTextField NomFournisseur;
    private javax.swing.JLabel NomFournisseur1;
    public static javax.swing.JComboBox<String> NumFournisseur;
    private javax.swing.JLabel NumFournisseur1;
    private javax.swing.JTextField Pays;
    private javax.swing.JLabel Pays1;
    private javax.swing.JTextField Prenom;
    private javax.swing.JLabel PrenomClient1;
    private javax.swing.JButton Retour;
    private javax.swing.JTextField Societe;
    private javax.swing.JLabel Societe1;
    private javax.swing.JTextField Telephone;
    private javax.swing.JLabel Telephone1;
    private javax.swing.JTextField Ville;
    private javax.swing.JLabel Ville1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
